### PR TITLE
added an input path field and a dorp-down menu for devices

### PR DESCRIPTION
**Pull request by R-Abbasi**
- Added an input path field, drop-down menu for devices, a button and a text

### CODE REVIEW

**Comment by bjoekeldude** [comment]
I tried reviewing the code just now. It is currently quite difficult to go through changes, since there are so many lines marked as changed:
image

We should find a way to have a consistent formatting.
There is a `pre-commit-hook` for clang format in the repo. But it looks like that hasn't been executed here, or am I mistaken?

**Comment by bjoekeldude** [comment]
I am sorry, can you tell me, which issue this is related to?
Maybe we should always put a screenshot of the feature into the `pr`.
It's really easy for me to get confused sometimes, sorry for that!

**Comment by bjoekeldude** [comment]
please `rebase` this pull-request to the current `head`. 
After that commit to this branch again and I will review the pr immediately.

**Comment by AKMaily** [comment]
After reviewing the latest pull request,  i think this request is outdated? @R-Abbasi

**Comment by R-Abbasi** [comment]
Yes, it's not required anymore and should be removed/closed, I believe.

**Pull request closed without merging**
