### PR TITLE
added file storage paths and write data to .csv files

### PR DESCRIPTION
**Pull request by R-Abbasi**
- Added file storage path fields with buttons and pop-up menu 
- Functionality to save data entered for vehicles on each or both devices inside `.cvs` files separately, associated with devices' names

### CODE REVIEW

**Review by bjoekeldude — CHANGES_REQUESTED** [review]
please add `.vscode/` to the `.gitignore` file.

**Comment by R-Abbasi** [comment]
https://github.com/skunkforce/OmniView/pull/74

**Comment by bjoekeldude** [comment]
> #74 Please also note that #73 is a complement to #72. So merging #73 will added the code for both `pr`s.

This is a bad decision IMHO. 
We should keep features clean. One Branch - One Feature - On Pull-Request.

I merged the change in `.gitignore`. If I am not mistaken here, you can now first rebase your current changes in the branch to `HEAD` and work from there.

Do I make sense?

**Comment by R-Abbasi** [comment]
The following output is the functionality of selecting one of the devices, as an example:
photo_2023-12-19_17-10-47

If `Device2` is selected too, there'll be a new pop-up window with a text field to input the second path which will be used to save data in `device2- ....csv` file.

**Comment by bjoekeldude** [comment]
Please add the correct `.gitignore` and commit+push once more.
Right now you committed the `.vscode/` as well.

**Review by bjoekeldude — APPROVED** [review]

**Pull request merged**
